### ISSUE TITLE
AddAccountToPost step doesn't work

### ISSUE THREAD

**Issue by mtitolo** [padrino/sample_blog_updated#1]
I'm doing the intro tutorial, and adding the migration for AddAccountToPost simply doesn't work. I'm on Padrino 0.13.1 and Ruby 2.3.0

[Details](https://gist.github.com/mtitolo/7949401f1a8b05df3fb6488546e13759)

After downloading the sample project, it appears that my project is missing the Account.rb model. Nowhere in the tutorial was I instructed to create this, and none of the commands included in the tutorial create this file.

Question: Where the heck did that Account model come from in this project? I *do* have accounts but the model doesn't appear to be visible elsewhere?

![screen shot 2016-04-27 at 8 59 33 pm](https://cloud.githubusercontent.com/assets/763698/14875005/03afb0d8-0cbb-11e6-9603-e4bda2d408de.png)

**Comment by wikimatze** [comment]
Hi @mtitolo I have this issue on my to-do list, this is something that has changed (think this the location of the models). I'll have deeper look into this and update the tutorial to fix this thing.

Thanks for reporting and enjoy Padrino.

**Comment by nesquena** [comment]
This updated blog tutorial is pretty new, sorry about the confusion here. Just verifying do you see https://github.com/padrino/sample_blog_updated/blob/master/models/account.rb in the models folder of your repo?

**Comment by mtitolo** [comment]
Ah so the Account model is in a different folder. This is unexpected. The sample project still works because there is an Account model in `app/models`. If you remove that, the error is reproducible with this repo.

**Comment by nesquena** [comment]
Padrino projects have multiple apps in a project, a bit like Django. Shared models live at root in "models" although models can also be put inside a particular app i.e app/models works just as well. Account should be generated automatically I believe during admin app generation step (which might have been left out of this new tutorial). 

If you add the Account model into "models", does that error to away?

**Comment by mtitolo** [comment]
@nesquena If `Account.rb` is in `/app/models` the migration runs fine. It does not work when `Account.rb` is in `/models`.

**Comment by mtitolo** [comment]
Also, just to note, the rest of the application works fine with Account in `/models`. It's just the migration that fails.

**Comment by wikimatze** [comment]
@nesquena I think the issue is `models/account.rb` needs to be in `app/models` you need to specify it during the project creation. I've stumbled into it during testing the tutorial again and was too lazy to update the guides. 

@mtitolo yeah, I'll need to make it clear, where you can put your models and if you want to change the location of them, what you have to change in the settings to make the project aware of such changes.

**Comment by nesquena** [comment]
Thanks for reporting this, we'll look into what's going on. And update the tutorial accordingly. For the record, the rake task should run with Account in either folder, we'll have to look into why that isn't the case with this repo.

**Comment by nesquena** [comment]
@wikimatze ok thanks for updating. 

@mtitolo ping us if you have any other issues, we are happy to help.

**Comment by wikimatze** [comment]
Found the solution: Migrations works, when you move the `models` folder into `app`. Hmm, but by default models are placed at the top of the application and it should work ...!

**Comment by wikimatze** [comment]
I found the solution for the problem:

You have to add the following line to `config/boots.rb`

```
Padrino.before_load do
  Padrino.dependency_paths << Padrino.root('models/**/*.rb')
end
```

I've updated the sample_code_updated code of this repository. @mtitolo can you run your examples again?

By the way I detected the broken admin interface layout, I'll fix it in another issue. At least you can see the app in action by now.

@nesquena I think it's a mistake that you have the path manually in the file, since the default path for fresh models is in the root `models` folder.

**Comment by wikimatze** [comment]
@mtitolo I've updated the guide and the example code, if you are fine with it, please close this issue.

**Comment by mtitolo** [comment]
Yep, looks good 👍  Thanks for the quick turnaround!
